config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  #devise_for :installs

  root 'home#index'

  namespace :admin do
    get 'home/index'
  	resources :home, only:[:index]
    resources :eventos
    resources :eventotipos
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/evento.rb
class Evento < ApplicationRecord
	belongs_to :eventotipo
	validates :fechainicial, presence: true
	validates :fechafinal, presence: true
	validates :descripcion, presence: true
	validates :eventotipo_id, presence: true
	attr_accessor :date_range

	  def all_day_event?
	    self.start == self.start.midnight && self.end == self.end.midnight ? true : false
	  end
end

app/models/eventotipo.rb
class Eventotipo < ApplicationRecord
	has_many :eventos
	validates :nombre, presence: true
end

app/models/install.rb
class Install < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  enum role: [ 'Administrador', 'Invitado' ]
  validates :nombre, presence: true
  validates :apellido_paterno, presence: true
  validates :apellido_materno, presence: true
  validates :role, presence: true
end

app/controllers/admin/eventos_controller.rb
class Admin::EventosController < ApplicationController
  layout 'admininterface'
  before_action :authenticate_user!
  
  def index
    @evento = Evento.all
  	#@evento = Evento.where(fechainicial: params[:start]..params[:end])
     #render(@evento, format: :json)
  end

  def new
  	@evento = Evento.new
  end

  def show
  end

  def edit
  	@evento = Evento.find(params[:id])
  end

  def create
  	@evento = Evento.new evento_params
  	if @evento.save 
      redirect_to ['admin',@evento], notice: "Evento creado"
    else
      render :new
    end
  end

  def update
    @evento = Evento.find(params[:id])
    if @evento.update evento_params
      redirect_to ['admin',@evento], notice: "Actualizado"
    else
      render edit
    end
  end

  def destroy
    @evento = Evento.find(params[:id])
    @evento.destroy
    redirect_to admin_eventos_path, notice: "Evento Eliminado"
  end

  private
    def set_event
      @evento = Event.find(params[:id])
    end

  	def evento_params
  		params.require(:evento).permit(:date_range,:fechainicial,:fechafinal,:descripcion,:eventotipo_id, :color)
  	end
end

app/controllers/admin/eventotipos_controller.rb
class Admin::EventotiposController < ApplicationController
	layout 'admininterface'
	before_action :authenticate_user!
  def index
  	@tipoeventos = Eventotipo.all
  end

  def new
  	@tipoeventos = Eventotipo.new
  end

  def show
  	@tipoeventos = Eventotipo.find(params[:id])
  end

  def edit
  	@tipoeventos = Eventotipo.find(params[:id])
  end

  def create
  	@tipoeventos = Eventotipo.new eventotipo_params
  	if @tipoeventos.save 
      redirect_to ['admin',@tipoeventos], notice: "Tipo de evento creado"
    else
      render :new
    end
  end

  def update
    @tipoeventos = Eventotipo.find(params[:id])
    if @tipoeventos.update eventotipo_params
      redirect_to ['admin',@tipoeventos], notice: "Actualizado"
    else
      render edit
    end
  end

  def destroy
    @tipoeventos = Eventotipo.find(params[:id])
    @tipoeventos.destroy
    redirect_to admin_eventotipos_path, notice: "Tipo de evento Eliminado"
  end

  private 
  	def eventotipo_params
  		params.require(:eventotipo).permit(:nombre)
  	end
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < ApplicationController
	layout 'admininterface'
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:nombre, :apellido_paterno, :apellido_materno, :role])
        devise_parameter_sanitizer.permit(:sign_in, keys: [:nombre, :apellido_paterno, :apellido_materno, :role])
    end

  private
    def after_sign_in_path_for(resource)
    	admin_home_index_path
      # El path a donde tu quieres que redirija cuando se ha logueado correctamente, ej. posts_path
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/helpers/eventotipos_helper.rb
module EventotiposHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/eventos/_form.html.erb
<%= render 'utilidades/errores', current_model: @evento %>
<%= form_for(['admin',@evento], html: {class: 'form-horizontal'}) do |f| %>
	<div class="form-group">
		<%= f.label :date_range, class: 'col-sm-2 control-label' %>
		<div class="col-sm-10">
			<%= f.text_field :date_range, class: "form-control input-sm date-range-picker" %>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :fechainicial, class: 'col-sm-2 control-label' %>
		<div class="col-sm-10">
			<%= f.text_field :fechainicial, as: :hidden, value: Date.today, class: 'form-control input-sm fechainicial_hidden'%>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :fechafinal, class: 'col-sm-2 control-label' %>
		<div class="col-sm-10">
			<%= f.text_field :fechafinal, as: :hidden, value: Date.today, class: 'form-control input-sm fechafinal_hidden' %>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :descripcion, class: 'col-sm-2 control-label' %>
		<div class="col-sm-10">
			<%= f.text_field :descripcion,  class: 'form-control' %>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :eventotipo_id, class: 'col-sm-2 control-label' %>
		<div class="col-sm-10">
			<%= f.select :eventotipo_id, Eventotipo.all.map{ |s| [s.nombre, s.id]}, class: 'form-control' %>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :color, class: 'col-sm-2 control-label' %>
		<div class="col-sm-10">
			<%= f.select :color, collection: [['Black','black'], ['Green','green'], ['Red','red']] %>
		</div>
	</div>
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
	    	<div class="actions">
	    		<%= f.submit 'Crear Evento', class: 'btn btn-info' %>
	    	</div>
	    </div>
	</div>
<% end %>

app/views/admin/eventos/edit.html.erb
<h1>Eventos - Editar</h1>
<%= render 'form' %>

app/views/admin/eventos/index.html.erb
<h1>Eventos - Inicio</h1>
<% if notice.present? %>
	<b><%= notice %></b>
<% end %>
<br>
<% if @evento.blank? %>
	<p style="color:#CC1C1C; font-weight:bold">No hay elementos en la Base de Datos</p>
<% else %>
	<table class="table table-striped table-hover">
		<thead>
			<tr>
				<th>ID</th>
				<th>Fecha Inicial</th>
				<th>Fecha Final</th>
				<th>Descripción</th>
				<th>Tipo de Evento</th>
				<th>Opciones</th>
			</tr>
		</thead>
		<tbody>
			<% @eventos.each do |e| %>
			<tr>
				<td><%= "#{e.id}"%></td>
				<td><%= "#{e.fechainicial}"%></td>
				<td><%= "#{e.fechafinal}"%></td>
				<td><%= "#{e.descripcion}" %></td>
				<td><%= "#{e.eventotipo.nombre}" %></td>
				<td>
					<%= link_to "Mostrar", admin_evento_path(e), :class => 'btn btn-mini btn-info'%>
					<%= link_to "Editar", edit_admin_evento_path(e), :class => 'btn btn-mini btn-default' %>
					<%= link_to "Eliminar", admin_evento_path(e), method: :delete, data: { confirm: "Eliminar Elemento?"}, :class => 'btn btn-mini btn-danger' %>
				</td>
			</tr>
			<% end %>
		</tbody>
	</table>
<% end %>

app/views/admin/eventos/new.html.erb
<h1>Eventos - Nuevo</h1>
<%= render 'form' %>

app/views/admin/eventos/show.html.erb
<h1>Eventos - Mostrar</h1>
<br>
<%= link_to "Nuevo Evento", new_admin_evento_path %>
<br>
<% if notice.present? %>
	<b><%= notice %></b>
<% end %>
<br>
<table>
	<thead>
		<tr>
			<th>Fecha Inicial</th>
			<th>Fecha Final</th>
			<th>Descripcion</th>
			<th>Tipo Evento</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td><%= "#{@evento.fechainicial}"%></td>
			<td><%= "#{@evento.fechafinal}"%></td>
			<td><%= "#{@evento.descripcion}" %></td>
			<td><%= "#{@evento.eventotipo.nombre}" %></td>
		</tr>
	</tbody>	
</table>

app/views/admin/eventotipos/_form.html.erb
<%= render 'utilidades/errores', current_model: @tipoeventos %>
<%= form_for(['admin',@tipoeventos], html: {class: 'form-horizontal'}) do |f| %>
	<div class="form-group">
		<%= f.label :nombre, class: 'col-sm-2 control-label' %>
		<div class="col-sm-10">
			<%= f.text_field :nombre, class: 'form-control' %>
		</div>
	</div>
	<div class="form-group">
	    <div class="col-sm-offset-2 col-sm-10">
	    	<div class="actions">
	    		<%= f.submit 'Crear Evento' %>
	    	</div>
	    </div>
  	</div>
<% end %>

app/views/admin/eventotipos/edit.html.erb
<h1>Tipo de eventos - Nuevo</h1>
<%= render 'form' %>

app/views/admin/eventotipos/index.html.erb
<h1>Tipos de Eventos - Inicio</h1>
<% if notice.present? %>
	<b><%= notice %></b>
<% end %>
<br>
<% if @tipoeventos.blank? %>
	<p style="color:#CC1C1C; font-weight:bold">No hay elementos en la Base de Datos</p>
<% else %>
	<table class="table table-striped table-hover">
		<thead>
			<tr>
				<th>ID</th>
				<th>Nombre Tipo Evento</th>
				<th>Opciones</th>
			</tr>
		</thead>
		<tbody>
			<% @tipoeventos.each do |e| %>
			<tr>
				<td><%= "#{e.id}"%></td>
				<td><%= "#{e.nombre}" %></td>
				<td>
					<%= link_to "Mostrar", admin_eventotipo_path(e), :class => 'btn btn-mini btn-info' %>
					<%= link_to "Editar", edit_admin_eventotipo_path(e), :class => 'btn btn-mini btn-default' %>
					<%= link_to "Eliminar", admin_eventotipo_path(e), method: :delete, data: { confirm: "Eliminar Elemento?"}, :class => 'btn btn-mini btn-danger' %>
				</td>
			</tr>
			<% end %>
		</tbody>
	</table>
<% end %>

app/views/admin/eventotipos/new.html.erb
<h1>Tipo de eventos - Nuevo</h1>
<%= render 'form' %>

app/views/admin/eventotipos/show.html.erb
<h1>Tipo de Evento - Mostrar</h1>
<br>
<%= link_to "Nuevo Evento", new_admin_eventotipo_path %>
<br>
<% if notice.present? %>
	<b><%= notice %></b>
<% end %>
<br>
<table>
	<thead>
		<tr>
			<th>Nombre</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td><%= "#{@tipoeventos.nombre}" %></td>
		</tr>
	</tbody>	
</table>

app/views/admin/home/index.html.erb
<div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <h1>Admin - Home</h1>
                    </div>
                </div>
            </div>

app/views/home/index.html.erb
<div class="container fondoInicio">
	<div class="row row-padding">
		<div class="col-md-12">
			<div class="container">
				<div class="row">
					<div class="col-md-8">
						<div class="calendar">
						</div>
					</div>
					<div class="col-md-4">
						<!--button id="create-note" class="btn btn-info">Agregar nota</button-->
						<div class="postit purple">
							<div class="tape">IMPORTANTE</div>
							    <div class="widget-content">
							      <p>Terminar la aplicación de Rails para que el profe no me repruebe.</p>
							    </div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<br>

<!--div id="dialog" title="Etiqueta Importante">
  <label for="name">Nueva nota importante</label>
  <input type="text" name="etiqueta" id="etiqueta" class="form-control">
</div-->

app/views/layouts/admin/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="nav-item"><%= link_to "Eventos", admin_eventos_path %></li>
        <li class="nav-item"><%= link_to "Tipos de Evento", admin_eventotipos_path %></li>
        <li class="nav-item active"><a>¡Hola, <%= current_user.email if user_signed_in? %> !</a></li>
        <li><%= link_to "Nuevo Evento", new_admin_evento_path %></li>
        <li><%= link_to "Nuevo Tipo de Evento", new_admin_eventotipo_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Página Inicial", root_path %></li>
        <li><%= link_to "[ Cerrar Sesión ]", destroy_user_session_path, method: :delete %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/admininterface.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Panel Administrador</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'layouts/admin/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Planificador</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'layouts/partials/banner' %>
  	<%= render 'layouts/partials/menu' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <%= render 'layouts/partials/footer' %>
  </body>
</html>

app/views/layouts/partials/_banner.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12 banner-border">	
			<h1 class="bannerHeader">Planificador Personal</h1>
		</div>
	</div>
</div>

app/views/layouts/partials/_footer.html.erb
<div class="footer">
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-12">
				Melina Castañeda Pírez - Facultad de Ingeniería UAA
			</div>
		</div>
	</div>
</div>

app/views/layouts/partials/_menu.html.erb
<nav class="navbar navbar-default">
  <ul class="nav navbar-nav">
    <% if user_signed_in? %>
      <li class="nav-item active"><a>¡Hola <%= current_user.email if user_signed_in? %> !</a></li>
      <li class="nav-item"><%= link_to "[ Panel Administrador ]", admin_home_index_path %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li class="nav-item"><%= link_to "[ Cerrar Sesión ]", destroy_user_session_path, method: :delete %></li>
    </ul>
    <% else %>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li class="nav-item active"><%= link_to "[ Iniciar Sesión ]", new_user_session_path %></li>
    </ul>
      
    <% end %>
</nav>

app/views/utilidades/_errores.html.erb
<% if current_model.errors.present? %>
	<div class="alert alert-danger">
		<button type="button" class="close" data-dismiss="alert

		">x</button>
		<p>¡¡Tienes errores!!</p>
		<ul>
			<% current_model.errors.messages.each do |m| %>
				<li><%= m %></li>
			<% end %>
		</ul>
	</div>
<% end %>